### ISSUE TITLE
Plugin / Command Ideas

### ISSUE THREAD

**Issue by ph7vc** [Arcbot-Org/Arcbot#11]
Just some of my ideas for things to do!

**Bot Management**
- unload / load plugins
- logout
- get debug info

**Trivia bot**
- This one is a given
- Asks questions on a topic, gives hints, checks answers, gives out score

**Steam integration**
- https://developer.valvesoftware.com/wiki/Steam_Web_API
- Search for players, get player stats, etc

**Admin**
- Ability to temporarily provision a voice channel for a group to use

**Chat features**
- ping
- image me x
- uptime
- insult people

**Voice features**
- Be able to stream sound effects over voice to a voice channel
- Perhaps response with a voice synthasizer

**Comment by ph7vc** [comment]
Had a funny plugin idea just now:

GrammarNazi:
- Randomly picks a message to sass the sender when they have spelled something wrong
- Wont happen frequently, but at random times while listening to a convo, could be funny to just interject and say stuff like, "@user you spelled 'grammar' wrong idiot #illiterate"

**Comment by ZetaHunter** [comment]
I do like that one, I had ideas of having *fix that would the last message in chat.
Also a s/replace/text/g irc thing.

**Comment by ph7vc** [comment]
Had another idea for a plugin command:

This one would probably only be useful on Discord; but be able to put people in a timeout state, so it will set their server role so they cant post in channel or speak. 

Probably useful to have a bunch of commands for editing permissions for users.

Another thing could be people could ask the bot to created them a temporary voice channel for a raid or something

**Comment by ZetaHunter** [comment]
That all sounds nice and stuff...
Except that implementing Roles and Voice is very specific to Discord Connector.
I have a @require decorator and am working on rewriting how Discord.py works (adding servers/channels/members cache, handling ready, etc) but Roles and Voice are very alien to me.

Nice idea thou
