### ISSUE TITLE
[core.Database] Persistence

### ISSUE THREAD

**Issue by ph7vc** [Arcbot-Org/Arcbot#22]
Since the use case I see is just storing Python dictionaries; I see no reason we shouldn't use MessagePack vs that of Pickle or Shelve.

This shows performance data for deserializing JSON with MessagePack vs Python's JSON library: http://wtanaka.com/node/8100

**Comment by ph7vc** [comment]
Current implementation uses Shelve which is Pickle under the hood; according to what I can find; this is significantly slower than directly serializing JSON with Python standard library. We are losing performance here

https://kovshenin.com/2010/pickle-vs-json-which-is-faster/

**Comment by ph7vc** [comment]
This also looks like a viable alternative: http://labs.codernity.com/codernitydb/

**Comment by ZetaHunter** [comment]
I would like to say that using a no-sql approach will in the long-term bite us in the ass, as such, I would like to suggest using actual tables for data store: http://www.sqlalchemy.org/

There is a lot more you can do with a relational database then with simple key-value.

**Comment by ph7vc** [comment]
>I would like to say that using a no-sql approach will in the long-term bite us in the ass, as such, I would like to suggest using actual tables for data store: http://www.sqlalchemy.org/
>
>There is a lot more you can do with a relational database then with simple key-value.

I don't see a use case for a full schema based data store. 

There is a lot of overhead with SQL, (creating schemas, normalizing data, joins across bot domains, etc). Something like SQLite I have considered; but again, I'd rather keep it simple. JSON is more than adequate for the 90% use case. 

I curious as to what you think the bot will need to have a full relational database to do

**Comment by ZetaHunter** [comment]
There are quite few good uses for relational storage for a bot.
If we want to be flexible we'd want to expose this storage to plugins.
Here is a big IRC bots repository with a lot of plugins some of which use SqlAlchemy.
https://github.com/CloudBotIRC/CloudBot/search?p=1&q=Table&type=Code&utf8=%E2%9C%93
Not to say it would simplify working on webUI if we go with Flask (Flask-SqlAlchemy), I don't see how we could have Arcbot plugin storage flexible if we use NoSQL...

**Comment by ph7vc** [comment]
Decided on using PeeWee for the database backend. It's an extremely lightweight ORM.

http://docs.peewee-orm.com/en/latest/index.html

I still need to consider a few things
- [ ] Thread-safe database transactions
- [ ] Abstraction to the plugin interface

**Comment by ph7vc** [comment]
Also decided that I'll expose both an ORM and a key store since peewee gives us both:
http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#KeyStore

**Comment by ZetaHunter** [comment]
Should use JSONKeyStore in that case.

On Oct 13, 2015, Patrick Hennessy <notifications@github.com> wrote:
>Also decided that I'll expose both an ORM and a key store since peewee
>gives us both:
>http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#KeyStore
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/Arcbot-Org/Arcbot/issues/22#issuecomment-147570180

-- Sent with K-@ Mail - the evolution of emailing.

**Comment by ph7vc** [comment]
Done for now: 0ba4785c39da325d5b23adb40ece8160728949f3
