### ISSUE TITLE
Create ArcBot organization. 

### ISSUE THREAD

**Issue by ZetaHunter** [Arcbot-Org/Arcbot#27]
Was just thinking of this, but maybe we could split off some things? Like plugins and future web ui into separate repositories in one unified ArcBot organization?
As an existing example: https://github.com/CloudBotIRC/

**Comment by ph7vc** [comment]
Will likely do this when I feel comfortable to declare a 'release' and announce the bot to a lot of people.

At the moment, I'm still working out a lot of kinks and adding core features; but will likely create an org in the future
