### ISSUE TITLE
[core.Connector] Replace current websockets / requests, deprecate Python2

### ISSUE THREAD

**Issue by ZetaHunter** [Arcbot-Org/Arcbot#37]
I've been looking into dropping Python 2 and use only Python 3.4+ in favor of using modern stuff like AsyncIO.

I've found a rather good library that handles HTTP Server, Client and WebSocket Client.
So with one library we can replace the `websockets` library and `requests` (maybe) library.
With one library: [aiohttp] (https://github.com/KeepSafe/aiohttp)
But it requires Python 3.4.1+ because it uses modern python feature set extensively.
We should not be held back by people who don't want to upgrade, drop em, ~~fuck em~~.

**Comment by ph7vc** [comment]
Interesting. 

I dont plan to do this for a while tho; what I have now works fine.

Perhaps this could be an improvement for the future

**Comment by ZetaHunter** [comment]
Well, I am looking toward doing that in my fork in near future. ( When I get done with Functional Data Classes )

**Comment by ZetaHunter** [comment]
Also wanted to mention that this could maybe be used for the WebUI :+1:
