### ISSUE TITLE
[core.ACL] ACL's

### ISSUE THREAD

**Issue by ph7vc** [Arcbot-Org/Arcbot#7]
Not sure how I want to implement this

**Comment by ph7vc** [comment]
blocked by #9 
I'll need a way to store user id and access amount to disk

**Comment by ph7vc** [comment]
Will need to load presistant user data when bot loads

will then need to load ACL's from disk

Put ACL defaults in config, so commands could do `@command("^ping", access=ACL.admin)`, would make it strictly admin command

**Comment by ph7vc** [comment]
Here are some considerations: (furgo storage for now)

1. How do I go from username in channel to uid? This could be challenging to do; would need a way to find and resolve conflicts
2. How much flexibility to give to the bot owner. Should access levels be restricted to a range? 
    * Owner getting 1000; and all other ranks are from 0-999
    * Should there even be considered ranks?
3. Command decorators should allow for `access=123`, but how could a bot owner configure commands in his bot? Should we leave it to going through each plugin and modifying access on a per command basis? This brings up another point; could we centralize plugin configs somewhere?
4. Some users could be white listed for certain commands? So they may not have access but are allow to use it

**Comment by ZetaHunter** [comment]
Blocked by #22

**Comment by ph7vc** [comment]
Implemented in 3fdbf1b
